### ISSUE TITLE
Cursor position is weird

### ISSUE THREAD

**Issue by hirenchauhan2** [wirekang/kysely-playground#1]
The characters are not being typed with respect to the cursor position. They're being typed by 2-3 characters before the cursor position.

**Comment by wirekang** [comment]
Could you provide more context such as OS or browser?

**Comment by hirenchauhan2** [comment]
I have seen it on Windows in Chrome browser. But, I think it was due to some font loading issues (maybe?). After reloading couple of times, it got resolved. It seems this issue is with the Monaco editor that you're using for code input.

**Comment by wirekang** [comment]
I've rewritten everything, so I'm closing this issue for now.
