### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by wirekang** [wirekang/kysely-playground#15]
Current playground is working fine, but I haven't had enough time when I wrote it. I plan to rewrite the project in February when I have plenty of free time to let the playground handles differences between multiple kysely versions (like `kysely/helpers/...` and new dialects) flexibly. The new playground will be fully backward compatible so don't worry about breaking shared links. The user-side will be pretty much the same as before too.

So, if you have some good ideas or bad experiences, this is a great time to improve it. Please provide your feedbacks.

**Comment by igalklebanov** [comment]
Hey 👋 

Thank you so much! 🙏 
As you know, we've been heavily using the playground in the docs or when communicating with one another on discord. It's been a blessing. 🌟 

Just a few ideas:

- I wonder if the version list and source code could be dynamically fetched and installed so it doesn't require PRs or commits every time a new Kysely version comes out.

- I wonder if we could make it more mobile-friendly.

- Aligning the starter example types with the ones used in Kysely's node tests would help come up with quicker demos on the fly.

**Comment by igalklebanov** [comment]
Another thing that would be really great: A "preview" version that downloads straight from `master` branch. 🤤

**Comment by wirekang** [comment]
@igalklebanov Thank you. I want minified/bundled Kysely so the playground always shows up fast without fetching hundreds of js/d.ts files dynamically. It'll also helps to make the playground more mobile-friendly. Scheduled workflows is what I'm considering(e.g. Checking a new commit/release every 30 minutes).
