### ISSUE TITLE
`executeTakeFirstOrThrow` doesn' fully work

### ISSUE THREAD

**Issue by koskimas** [wirekang/kysely-playground#37]
Seems to give an error in the SQL panel

https://kyse.link/ars$&

**Comment by wirekang** [comment]
I will revert the default result rows from `[]` to `[{}]` like old playground.
 
It was intended behavior. You can set the result via `$playground` object: [link.](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jeAD20RgAIoA7GMBAMwEMBjMUgEXpnoCN6kXgAOhVKkwVBFDBJUpQcJHkIMpDAkUA5gG4hIgL7b5Y1ZgD6AN0kB3abJ0KjCU1CWkVarXf1DdQkABoQAEcAVxpMfAASbAAbekx1BDhgiggAOgQpYOiyAF5ZUkTrGQBtYEUZARBaODhKv1ILMGsTRiSqGQBmUl0AXW6DIVaKFQLM7NI8+kt6WFIILjtUvmiwRhgAMUSAWwAKSodJJFJeUUqASkWV2hgAKThKPfkRebsFUiWwFbXNuF398VMjWs51eCg+XxgOx2YC4ZwmAD5SMVQW9-sYTM46ij7FxUrQKKlWskYABBaLRAA8FGCWy4NHhOzOqV4exAQJabRg5z82J6FyeYISSWwACFMKyHE4ICCBSJmUgJWZuaCdgAre4UOE5RHqyipOAUABKYFoEtSmP8pEqOTqVvAZlSkox0pAZx58n5cuWq1J5IlMq9nx9UJhWvhoJheIJrXoKyQzEVqXZRKotsj0VgOwADGcmSzKkCkBzicqPYswARVsFqAAVegAazA6ygyBgAHkEDWABaFRkDChRWLxRLJNLRODqHYZJBZGBnAwgXQBaCxn34YgqBJSfwgeuYZbhdAgLC4fCcdQ7ij0LZ4VAgLOpABMAHYn4uAl3nGAazhb6pQroQA)
