### ISSUE TITLE
Modifying the schema doesn't re-evaluate the script

### ISSUE THREAD

**Issue by koskimas** [wirekang/kysely-playground#45]
Hey!

Let's say I write a query to a non-existent table `foo`, there's correctly an error in the editor since that table doesn't exist. Now if I go to the schema editor and add that table, the error doesn't go away. I need to edit the script for the error to disappear. Could the script be updated also when the schema is modified? I think it used to be that way?

**Comment by wirekang** [comment]
Fixed. There is a debouncing on "re-evaluating" which is quite high by default. Turn on the `lower-debounce-time` option before you run out of patience.

**Comment by koskimas** [comment]
Awesome! The default debounce is good IMO.
