### ISSUE TITLE
Possibly an invalid URL generated

### ISSUE THREAD

**Issue by koskimas** [wirekang/kysely-playground#53]
Hi,

I might've messed something up, but I'm pretty sure kyse.link gave me this URL https://kyse.link/SH-8, which doesn't seem to work. As I said, I might've accidentally erased a part of it or something, but here it is in case you want to check if something went wrong.

kthxby

**Comment by koskimas** [comment]
I know what happened. The actual link is https://kyse.link/SH-8. including the trailing dot. At least github and discord exclude trailing dots from links.

<img width="280" alt="Screenshot 2024-05-24 at 14 15 41" src="https://github.com/wirekang/kysely-playground/assets/846508/5a2cf9d2-80f8-4a59-9a9a-89ba47e285a6">

**Comment by wirekang** [comment]
Now all identifiers will be composed of numbers and alphabets.
