### ISSUE TITLE
Internals showing up

### ISSUE THREAD

**Issue by koskimas** [wirekang/kysely-playground#61]
There's something weird going on in this playground, at least in mobile mode https://kyse.link/YPo5w.

![Screenshot_2024-09-19-08-19-22-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/8a6d8cd1-0ebb-4c2b-a602-6ec9503e8d56)

The internal code is shown.

**Comment by wirekang** [comment]
There is the internal code in the shared data, which shouldn't happen.

It seems the auto-import feature corrupting the internal code is the reason. I'll fix it(I've already prepared it, but something went wrong), so please avoid using auto-import feature for now.

<img width="318" alt="image" src="https://github.com/user-attachments/assets/2cdec970-330e-49b0-81a9-16ef9a717880">

If you haven't used the feature, there must be something else corrupting the internal code, so please give me a hint.

**Comment by koskimas** [comment]
Thanks for looking into this!

I probably did use auto import when writing the original playground, but it was fine when I finished it. Only once I clicked the link (a day later) it had that internal code.

I use auto import all the time by the way and haven't seen this happen before.

**Comment by wirekang** [comment]
To make things clear, please confirm that you're using playground with `format-before-save` disabled.
![image](https://github.com/user-attachments/assets/b7058534-7ace-46f0-9941-4ec1b6745e19)

**Comment by wirekang** [comment]
Fixed, and a new link: https://kyse.link/q1qXA
